Adding my student file and associated media
DHS-23-24-CSA-Schick/GreenfootSeatingChartMaster2023-24-P4 pull request #8
Opened 2023-09-04 01:12 UTC by RyanKim124

2023-09-06 18:02 UTC, BardiaAnvari submitted a review, later dismissed
LGTM!

2023-09-06 18:34 UTC, anirudhb requested changes
Please add your Classroom.java changes

2023-09-06 22:36 UTC, RyanKim124 commented
Added the classroom file changes, should be good now imo

2023-09-07 03:48 UTC, anirudhb approved these changes
lgtm

2023-09-07 04:00 UTC, anirudhb requested changes

2023-09-07 04:00 UTC, anirudhb commented on Classroom.java
> +        kilgoretrout.assignSeat();
```suggestion
        ryankim.assignSeat();
```

2023-09-07 04:22 UTC, anirudhb approved these changes
lgtm

2023-09-07 04:23 UTC, merged