adding student desk group methods -group 6
DHS-23-24-CSA-Schick/GreenfootSeatingChartMaster2023-24-P4 pull request #9
Opened 2023-09-04 06:46 UTC by NithilaSadheesh

leave all classroom changes
added methods to assign student to group number and find all student names from group number

(also, it says my dads name but this is from nithila sadheesh)

2023-09-06 18:11 UTC, anirudhb requested changes
Does this compile?

2023-09-06 18:11 UTC, anirudhb commented on StudentDeskGroup.java
> +                desk.setDeskGroup(1);
`Student` doesn't have `setDeskGroup`

2023-09-06 23:43 UTC, NithilaSadheesh commented on StudentDeskGroup.java
> +                desk.setDeskGroup(1);
setDeskGroup is a public method in StudentDesk.java and we are accessing it here

2023-09-07 03:47 UTC, anirudhb submitted a review, later dismissed
lgtm

2023-09-07 03:57 UTC, anirudhb approved these changes

2023-09-07 03:58 UTC, merged